


@startuml



    package domain{
        class Address{
            country : Country
            city : City
            state : State
            streetAddress : StreetAddress
            zip : Zip
        }

        class Zip{
            code : String
        }

        class City{
            name : String
        }

        class StreetAddress{
            name : String
        }

        class State{
            name : String
        }

        class Country {
            name : String


        }

        class SuperCharger{
            address : Address
        }

        class Sale{
            numberVehicles : int
            typeVehicle : String
            country : Country
            year : int
        }


        class Stalls{
        }

        class PowerKw{
        }

        class GPS{
        }

        class Elevm{
        }

        class Status{
        }
        class YearPair{
        }
    }
    package structures{
        class StructureChargerClusterPOI{}
        class StructureChargersByCountry{}
        class StructureCityChargers{}
        class StructureDecreaseInSales{}
        class StructureQuotaReport{}
        class StructureStockCapacity{}
        class StructureWithMinAutonomy{}
        class StructureEvolutionNumberVehicles{}

    }

    package tasks{
        class TaskChargerClusterByPOI{}
        class TaskChargersByCountry{}
        class TaskCityChargers{}
        class TaskDecreaseInSales{}
        class TaskQuotaReport{}
        class TaskStockCapacity{}
        class TaskWithMinAutonomy{}
        class TaskEvolutionNumberVehicles{}
    }



    package fileIO{
        interface Files{}
    }

    package utils{
        class UtilsFile{}
        class UtilsMap{}
        class UtilsList{}

    }


Address "1" --o "1" Country
Address "1" --o "1" City
Address "1" --o "1" StreetAddress
Address "1" --o "1" Zip
Address "1" --o "1" State

SuperCharger "1" --o "1" Address
SuperCharger "1" -- "1" Status
SuperCharger "1" -- "1" GPS
SuperCharger "1" -- "1" PowerKw
SuperCharger "1" -- "1" Stalls
SuperCharger "1" -- "1" Elevm

StructureChargerClusterPOI "1" --- "1" TaskChargerClusterByPOI : has >
StructureChargersByCountry "1" -- "1" TaskChargersByCountry : has >
StructureCityChargers "1" -- "1" TaskCityChargers : has >
StructureDecreaseInSales "1" -- "1" TaskDecreaseInSales : has >
StructureWithMinAutonomy "1" --- "1" TaskWithMinAutonomy : has >
StructureEvolutionNumberVehicles "1" -- "1" TaskEvolutionNumberVehicles : has >
StructureQuotaReport "1" --- "1" TaskQuotaReport : has >
StructureStockCapacity "1" --- "1" TaskStockCapacity : has >

StructureChargerClusterPOI "1" --- "1" Files : implements >
StructureChargersByCountry "1" -- "1" Files : implements >
StructureCityChargers "1" -- "1" Files : implements >
StructureDecreaseInSales "1" -- "1" Files : implements >
StructureWithMinAutonomy "1" --- "1" Files : implements >
StructureEvolutionNumberVehicles "1" -- "1" Files : implements >
StructureQuotaReport "1" --- "1" Files : implements >
StructureStockCapacity "1" --- "1" Files : implements >

StructureChargerClusterPOI "1" ----- "1" Bootstrap : has >
StructureChargersByCountry "1" --- "1" Bootstrap : has >
StructureCityChargers "1" ---- "1" Bootstrap : has >
StructureDecreaseInSales "1" ---- "1" Bootstrap : has >
StructureWithMinAutonomy "1" --- "1" Bootstrap : has >
StructureEvolutionNumberVehicles "1" ---- "1" Bootstrap : has >
StructureQuotaReport "1" --- "1" Bootstrap : has >
StructureStockCapacity "1" --- "1" Bootstrap : has >

Bootstrap "1" -- "1" UtilsFile : gets


@enduml